### ISSUE TITLE
Use strict mode

### ISSUE THREAD

**Issue by mnolte** [Schaakzet/schaakzet.github.io#14]
You can use strict mode in all your programs. It helps you to write cleaner code, like preventing you from using undeclared variables.

1. Implement ["use strict"](https://www.w3schools.com/js/js_strict.asp)
2. Declare [undeclared variables](https://eslint.org/docs/latest/rules/no-undef)
3. Comment [unused variables](https://eslint.org/docs/latest/rules/no-unused-vars) and create issues for addressing them.

**Comment by Danny-Engelman** [comment]
Excellent example why we are not like a normal company. 

Strict mode prevents errors, but we do want to learn from errors.  
Our main objective is to learn, not to produce applications.

Strict mode is a bit like having to put your pencil back into the box before you can use another color.

![](https://c8.alamy.com/comp/2GR7R23/drawing-with-colored-pencils-on-table-2GR7R23.jpg)

**Comment by mnolte** [comment]
So I understand we don't want this then. Closing the issue.
