### ISSUE TITLE
Strings are not always consistently quoted

### ISSUE THREAD

**Issue by mnolte** [Schaakzet/schaakzet.github.io#17]
Strings are not always consistently quoted.

https://eslint.org/docs/latest/rules/quotes

**Comment by Danny-Engelman** [comment]
Totally agree;

When you are ONE Team and play Champions League

We will have team members with all levels of knowledge. And we're not going to "teach" them something a next team will call "wrong"

That means its MTW (Make That Work)
And will also mean each team member will learn to look twice (when something is wrong), you learn the most from mistakes.
