### ISSUE TITLE
Expected getter to always return a value

### ISSUE THREAD

**Issue by mnolte** [Schaakzet/schaakzet.github.io#18]
https://eslint.org/docs/latest/rules/getter-return

https://github.com/Schaakzet/schaakzet.github.io/blob/10c16ce88d61bb301563ec824eae3d0a3decf2bf/webcomponents/chess-board.js#L550

**Comment by Danny-Engelman** [comment]
That's why we don't let ESLint program; you get bloated code

````
   get lastMove() {
        if (this.chessMovesHistory.length) {
          return this.chessMovesHistory.lastMove;
        }
        return undefined; // keep ESlint quiet, every programmer should know functions return undefined by default
      }
  ````
