### ISSUE TITLE
Unnecessary escape character

### ISSUE THREAD

**Issue by mnolte** [Schaakzet/schaakzet.github.io#20]
https://eslint.org/docs/latest/rules/no-useless-escape

https://github.com/Schaakzet/schaakzet.github.io/blob/10c16ce88d61bb301563ec824eae3d0a3decf2bf/webcomponents/chess-boards.js#L20

**Comment by faiz-ali-khan-developer** [comment]
Hey can you assign m this issue

**Comment by Danny-Engelman** [comment]
Nice catch ESLint

``"1|2#3".split(/[\n|#]/)``

indeed splits on the pipe, I thought it required an escape, because the pipe character has a meaning in Regex
