### ISSUE TITLE
Move function declaration to function body root

### ISSUE THREAD

**Issue by mnolte** [Schaakzet/schaakzet.github.io#21]
https://eslint.org/docs/latest/rules/no-inner-declarations

1. https://github.com/Schaakzet/schaakzet.github.io/blob/10c16ce88d61bb301563ec824eae3d0a3decf2bf/webcomponents/chess-piece.js#L246
2. https://github.com/Schaakzet/schaakzet.github.io/blob/10c16ce88d61bb301563ec824eae3d0a3decf2bf/webcomponents/chess-piece.js#L260
3. https://github.com/Schaakzet/schaakzet.github.io/blob/10c16ce88d61bb301563ec824eae3d0a3decf2bf/webcomponents/chess-piece.js#L279

**Comment by Danny-Engelman** [comment]
Het zijn bewust ``function`` voor de leesbaarheid; en in JS worden deze sowieso al 'gehoist' naar boven (binnen de scope).

We kunnen ook als arrow function schrijven (doe ik meestal tegenwoordig), dan zeurt ESLint niet

``const /* function */ isCastling = () =>``

Zo leest het wel duidelijk dat het een FUNCTIE is, en geen constante
