### ISSUE TITLE
chess-show-captured-pieces

### ISSUE THREAD

**Issue by spoofmyarp** [Schaakzet/schaakzet.github.io#24]
1. chess-show-captured-pieces depends on evt.detail.chessboard which is NOT being held in Database. Therefore when resuming Match, the Captured Pieces are lost.
2. Repair this.

**Comment by Danny-Engelman** [comment]
Refactor, nu wordt voor iedere Move gecheckt of er een stuk geslagen is.

Code wise makkelijker om de **huidige** FEN te vergelijken met de startboard FEN, dan weet je welke stukken niet meer op het bord staan.

in chess-board.js ben ik al begonnen met ``allPieces``, ``boardPieces`` en ``capturedPieces``
