### ISSUE TITLE
setTimeouts minimaliseren.

### ISSUE THREAD

**Issue by mnolte** [Schaakzet/schaakzet.github.io#7]
Gebruik van timeouts minimaliseren. Deze maskeren over het algemeen een ander probleem.

**Comment by Danny-Engelman** [comment]
Correct, alleen is met Web Components zo dat met:

````
<my-component>
  MORE HTML
</my-component>
````

The ``MORE HTML`` pas geparsed is NA dat de ``connectedCallback`` is aangeroepen.
Oftewel, de ``connectedCallback`` vuurt op de OPENING tag <my-component>
Die MORE HTML kan namelijk gigantische zijn; en men wilde niet dat de Web Component helemaal niets meer kon doen totdat alles geparsed is.

Dus ``<chess-board>`` weet in de ``connectedCallback`` nog niets over zijn inhoud 

De enige manier om dan zeker te weten dat alle ``innerHTML`` er is, is te wachten tot de Event Loop leeg is.

``setTimeout(..,0)`` is daar de simpelste methode voor.

Libraries/Tools als Lit, Stencil schermen je hiervoor af... en _a fool with a tool, is still a fool_

Goede video over de Eventloop: https://www.youtube.com/watch?v=8aGhZQkoFbQ&vl=en
